#!/bin/bash

# This triggers each integration test in its own tmux pane, in parallel.
# It sets a different (temporarily) kubeconfig location for each test
# to avoid config file locking issues.
# To be run in a tmux session, under linkerd2's repo root dir after having
# built all the docker images (with bin/docker-build)

system=$(uname -s)
rootdir=$(pwd)

if [ "$system" = Darwin ]; then
  bin=$rootdir/target/cli/darwin/linkerd
elif [ "$system" = Linux ]; then
  bin=$rootdir/target/cli/linux-amd64/linkerd
else
  echo "unknown system: $system" >&2
  exit 1
fi

# build linkerd executable if it does not exist
if [ ! -f "$bin" ]; then
  "$bindir"/build-cli-bin >/dev/null
fi

targets=$(bin/tests -h | grep -oP '(?<=name flag: \[).*(?=\])')
i=0
for target in ${targets[@]}; do
  tmux split-window
  tmux select-layout tiled
  tmux send-keys -t $i "cd $rootdir; KUBECONFIG=$(mktemp -d -t kubeconfig.XXX)/config bin/tests --name $target ${bin}" ENTER
  ((i++))
done
